ALTER TABLE ascp_proposal_workflows
    ADD COLUMN chain_action text;

UPDATE ascp_proposal_workflows
SET chain_action = CASE governance_action->>'type'
    WHEN 'CALL_ESCROW_ADD_VERIFIER' THEN 'CALL_ESCROW_ADD_VERIFIER'
    WHEN 'CALL_ESCROW_REVOKE_VERIFIER' THEN 'CALL_ESCROW_REVOKE_VERIFIER'
    WHEN 'CALL_ESCROW_PAUSE' THEN 'CALL_ESCROW_PAUSE'
    WHEN 'SPEND_AUTHORIZER' THEN 'SPEND_SET_AUTHORIZER'
    WHEN 'SPEND_ALLOWLIST' THEN 'SPEND_SET_ALLOWLIST'
    WHEN 'SPEND_CAPS' THEN 'SPEND_SCHEDULE_CAPS'
    WHEN 'SPEND_PAUSE' THEN 'SPEND_PAUSE'
    WHEN 'SPEND_INVALIDATE_NONCES' THEN 'SPEND_INVALIDATE_NONCES'
    WHEN 'DIRECTORY_APPROVE' THEN 'DIRECTORY_PUBLISH'
    WHEN 'DIRECTORY_CANCEL' THEN 'DIRECTORY_CANCEL'
END
WHERE governance_action IS NOT NULL;

ALTER TABLE ascp_proposal_workflows
    ADD CONSTRAINT ascp_proposal_workflows_chain_action CHECK (
        chain_action IS NULL OR chain_action IN (
            'CALL_ESCROW_ADD_VERIFIER','CALL_ESCROW_REVOKE_VERIFIER','CALL_ESCROW_PAUSE',
            'DIRECTORY_PUBLISH','DIRECTORY_CANCEL','DIRECTORY_SET_PUBLISHER','DIRECTORY_SET_PAUSER',
            'DIRECTORY_PAUSE_SELLER','DIRECTORY_UNPAUSE_SELLER',
            'DIRECTORY_REVOKE_QUOTE_KEY','DIRECTORY_UNREVOKE_QUOTE_KEY',
            'AGENT_REGISTER','AGENT_UPDATE_POLICY','AGENT_SET_STATUS','AGENT_SET_REGISTRY_ADMIN',
            'SPEND_SET_AUTHORIZER','SPEND_SET_ALLOWLIST','SPEND_SCHEDULE_CAPS','SPEND_PAUSE',
            'SPEND_INVALIDATE_NONCES','SAFE_ENABLE_MODULE','SAFE_DISABLE_MODULE',
            'SAFE_ADD_OWNER_WITH_THRESHOLD','SAFE_REMOVE_OWNER','SAFE_SWAP_OWNER','SAFE_CHANGE_THRESHOLD'
        )
    ),
    ADD CONSTRAINT ascp_proposal_workflows_chain_action_kind CHECK (
        chain_action IS NULL OR
        (kind = 'VERIFIER_GOVERNANCE' AND chain_action IN ('CALL_ESCROW_ADD_VERIFIER','CALL_ESCROW_REVOKE_VERIFIER')) OR
        (kind = 'PAYOUT_CHANGE' AND chain_action = 'DIRECTORY_PUBLISH') OR
        (kind = 'SIGNER_CAPS' AND chain_action = 'SPEND_SCHEDULE_CAPS') OR
        (kind = 'DIRECTORY_CANCEL' AND chain_action IN (
            'DIRECTORY_CANCEL','DIRECTORY_PAUSE_SELLER','DIRECTORY_UNPAUSE_SELLER',
            'DIRECTORY_REVOKE_QUOTE_KEY','DIRECTORY_UNREVOKE_QUOTE_KEY'
        )) OR
        (kind = 'ROLE_ADMIN' AND chain_action IN ('AGENT_REGISTER','AGENT_UPDATE_POLICY','AGENT_SET_STATUS')) OR
        (kind = 'MODULE_GOVERNANCE' AND chain_action IN (
            'SPEND_SET_AUTHORIZER','SPEND_SET_ALLOWLIST','SPEND_INVALIDATE_NONCES',
            'SAFE_ENABLE_MODULE','SAFE_DISABLE_MODULE'
        )) OR
        (kind = 'BREAK_GLASS' AND chain_action IN (
            'CALL_ESCROW_PAUSE','SPEND_PAUSE','DIRECTORY_SET_PUBLISHER','DIRECTORY_SET_PAUSER',
            'AGENT_SET_REGISTRY_ADMIN','SAFE_ADD_OWNER_WITH_THRESHOLD','SAFE_REMOVE_OWNER',
            'SAFE_SWAP_OWNER','SAFE_CHANGE_THRESHOLD'
        ))
    ),
    ADD CONSTRAINT ascp_proposal_workflows_chain_action_binding CHECK (
        (governance_action IS NULL AND chain_action IS NULL) OR
        (governance_action IS NOT NULL AND chain_action IS NOT NULL)
    );

CREATE OR REPLACE FUNCTION flowops_guard_workflow_chain_action()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.chain_action IS DISTINCT FROM NEW.chain_action THEN
        RAISE EXCEPTION 'proposal workflow chain action is immutable' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS ascp_proposal_workflows_chain_action_guard ON ascp_proposal_workflows;
CREATE TRIGGER ascp_proposal_workflows_chain_action_guard
BEFORE UPDATE ON ascp_proposal_workflows
FOR EACH ROW EXECUTE FUNCTION flowops_guard_workflow_chain_action();
